background = {{colors.background.dark.hex}}
foreground = {{colors.on_surface_variant.dark.hex}}
cursor-color = {{colors.primary.dark.hex | lighten: 40}}

selection-background = {{colors.surface_container_high.dark.hex}}
selection-foreground = {{colors.on_surface.dark.hex}}

palette = 0={{colors.surface.dark.hex}}
palette = 1={{colors.surface_variant.dark.hex}}
palette = 2={{colors.primary.dark.hex}}
palette = 3={{colors.tertiary.dark.hex}}
palette = 4={{colors.primary_container.dark.hex | lighten: 20}}
palette = 5={{colors.primary_container.dark.hex | lighten: 30}}
palette = 6={{colors.primary_container.dark.hex | lighten: 40}}
palette = 7={{colors.on_surface_variant.dark.hex}}
palette = 8={{colors.outline.dark.hex}}
palette = 9={{colors.inverse_primary.dark.hex | lighten: 10}}
palette = 10={{colors.primary.dark.hex | lighten: 50}}
palette = 11={{colors.tertiary_container.dark.hex | lighten: 40}}
palette = 12={{colors.primary.dark.hex | lighten: 50}}
palette = 13={{colors.inverse_primary.dark.hex | lighten: 50}}
palette = 14={{colors.primary_container.dark.hex | lighten: 50}}
palette = 15={{colors.primary.dark.hex | lighten: 25}}
