background {{colors.background.dark.hex}}
foreground {{colors.on_surface_variant.dark.hex}}
cursor {{colors.primary.dark.hex | lighten: 40}}

selection_background {{colors.surface_container_high.dark.hex}}
selection_foreground {{colors.on_surface.dark.hex}}

color0 {{colors.surface.dark.hex}}
color1 {{colors.error.dark.hex}}
color2 {{colors.primary.dark.hex}}
color3 {{colors.tertiary.dark.hex}}
color4 {{colors.primary.dark.hex}}
color5 {{colors.primary_container.dark.hex | lighten: 30}}
color6 {{colors.primary_container.dark.hex | lighten: 40}}
color7 {{colors.on_surface_variant.dark.hex}}

color8 {{colors.outline.dark.hex}}
color9 {{colors.inverse_primary.dark.hex | lighten: 10}}
color10 {{colors.green.dark.hex}}
color11 {{colors.tertiary_container.dark.hex | lighten: 40}}
color12 {{colors.primary.dark.hex | lighten: 50}}
color13 {{colors.inverse_primary.dark.hex | lighten: 50}}
color14 {{colors.primary_container.dark.hex | lighten: 50}}
color15 {{colors.primary.dark.hex | lighten: 25}}
